### PR TITLE
structure upload

### PR DESCRIPTION
**Pull request by reinhardt**
Enables local document preview generation using slc.docconv

### CODE REVIEW

**Comment by pilz** [comment]
Jenkins was not able to get collective.documentviewer and slc.docconv. I added that to the branch but I see no way to extend your pull request (kind of understandable). If you can integrate my last commits, I think, jenkins and travis would be happy again.

**Comment by reinhardt** [comment]
Thanks @pilz! I do see your commits above. As long as you commit to the same branch the pull request is automatically extended afaik.

However, collective.documentviewer is a dependency of slc.docconv, which is pulled in by the "local" extra, so I don't see what difference it would make to add it here. (Besides, it's semantically wrong, because docconv.client does not directly depend on it.)

You mentioned the failing jenkins build of ploneintranet.suite master. Not sure if you're referring to that, but it complained about a missing "local" extra, which I don't understand at all, because the code to pull that in is not in the master branch of the suite. To me it looks like it uses the latest commit, no matter what branch. In [build #1888](http://jenkins.ploneintranet.net/job/Plone%20Intranet%20Suite%20Master/1888/) that was ploneintranet/ploneintranet.suite@04dda547, which was not merged to master at that time.

If anyone can enlighten me what's happening here I'll be grateful.

The Docconv Client job on jenkins is still red, and I understood why just now: the "test" extra must also depend on slc.docconv. I've added that and will keep an eye on the job.

Travis is green for this branch and [has been since before your commits](https://travis-ci.org/ploneintranet/ploneintranet.docconv.client/builds/53067983).

**Comment by pilz** [comment]
This needs to configure documentconverter to use /tmp as default

**Comment by reinhardt** [comment]
/tmp is now set as default storage_location by slc.docconv (which is a dependency of this package).

**Comment by pilz** [comment]
Nice, when all is properly installed, already creating demo content triggers the preview generation. Takes a good bit longer now, but that is desired ;)

**Comment by reinhardt** [comment]
Thanks! I suppose the suite pull request was a little premature - it would make sense to merge that only when the robot tests are done. What do you think?
https://github.com/ploneintranet/ploneintranet.suite/pull/45

**Pull request merged**
